# Generated by Django 3.1.2 on 2020-10-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkuser',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='lat',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='lng',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='networkuser',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
